### ISSUE TITLE
 where is code for confidence interval

### ISSUE THREAD

**Issue by Sandy4321** [debangshu16/Crime-Prediction#1]
great code thanks
only 
but also, we can draw a confidence interval around our predictions to reduce uncertainty.

may you help to find where is code for confidence interval

**Comment by debangshu16** [comment]
Hi,
Please look at the sections "Checking Linear Regression Assumptions" and "Evaluating on Unseen data" of the notebook "Crime_Prediction_Normalized_Regression_Best_Final_PLUS_SVR_RFR.ipynb" for the confidence interval.
